% definition of parameters
muB = 9.2740100783e-24;
hbar = 1.05457182e-34;
gperp = 2;
gparalell = -18.225;
gtensor = [
    gperp, 0, 0;
    0, gparalell, 0;
    0, 0, gperp];
dg = abs(gperp-gparalell);
rho = 5275.8;
W = 30e-9;
A = W*W;
Iy = A^2/12;
I = 2*Iy;
mu = 4.5962E10;
C = 0.13976323261691082*A^2*mu;
ld = 30e-9;
E=1.2983E11;
bx = [1;0;0];
by = [0;1;0];
bz = [0;0;1];



% Read raw data generated by comsol project
dispersion = read_comsol_file('modes.txt');
Nmodes = max(dispersion(:, 7));

% PLot the dispersion relation (Fig. 3 in manuscript)
plot_dispersions(dispersion, Nmodes);
qq = linspace(0,max(abs(dispersion(:,2))),100);
fL = qq*sqrt(E/rho)/2/pi;
fT = qq*sqrt(C/rho/I)/2/pi;
fF = qq.^2*sqrt(E*Iy/rho/A)/2/pi;
hold on;
plot(qq*1e-9,fL*1e-9, 'LineWidth',3, 'Color', 'magenta');
plot(qq*1e-9,fT*1e-9, 'LineWidth',3, 'Color', 'blue');
plot(qq*1e-9,fF*1e-9, 'LineWidth',3, 'Color', 'red');
hold off;
ylim([0,70]);
box on
exportgraphics(gcf,'dispersion.pdf','ContentType','vector')


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Plot the relaxation rates (Fig. 4(b))
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
figure;
modes = unique(dispersion(:,7));
[Gamma, ff] = relaxation_from_dispersion_table(dispersion, modes, bx, ld, rho, A, gtensor, hbar);
plot_with_inf(ff, Gamma, '-');
hold on;
[Gamma, ff] = relaxation_from_dispersion_table(dispersion, modes, by, ld, rho, A, gtensor, hbar);
plot_with_inf(ff, Gamma, '-');
set(gca,'ColorOrderIndex',5);
[Gamma, ff] = relaxation_from_dispersion_table(dispersion, modes, bz, ld, rho, A, gtensor, hbar);
plot_with_inf(ff, Gamma, '-');
set(gca,'ColorOrderIndex',1);
ff = linspace(0.9*1e-1,70); % in GHz
omegaL = 2*pi*ff*1e9;
Gammatx = dg^2*hbar/4/gperp^2/sqrt(rho*I*C)*exp(-omegaL.^2*ld^2*rho*I/2/C).*omegaL;
plot_with_inf(ff, Gammatx, '--');
Gammafy = (omegaL.^6*hbar^4/rho/A/E^3/Iy^3).^(1/4)*dg^2/gparalell^2/8.*exp(-omegaL.*ld^2/2*sqrt(rho*A/E/Iy));
Gammaty = hbar*omegaL*dg^2/4/gparalell^2/sqrt(rho*I*C).*exp(-omegaL.^2*ld^2*rho*I/2/C);
Gammay = Gammafy+Gammaty;
plot_with_inf(ff, Gammay, '--')
set(gca,'ColorOrderIndex',5);
Gammafz = (dg^8*hbar^6*omegaL.^6/gperp^8/hbar^2/rho/A/E^3/Iy^3).^(1/4)/8.*exp(-omegaL.*ld^2/2*sqrt(rho*A/E/Iy));
plot_with_inf(ff, Gammafz, '--')
xlabel('Larmor frequency, $f_\mathrm{L}$ (GHz)', 'Interpreter', 'latex', 'FontName', 'Times');
ylabel('Relaxation rate, $\Gamma$ (1/s)', 'Interpreter', 'latex');
hold off
legend('$B || x$', '$B || y$', '$B || z$', 'Location','northwest', 'Interpreter', 'latex');
fontsize(20, "points");
fontname('Times')
ylim([1e-2,5e2]);
yticks([1e-2, 1e-1, 1, 1e1, 1e2]);
xlim([0.9*1e-1, 70]);
xticks([1e-1, 1, 1e1]);
exportgraphics(gcf,'relaxationrates_fL.pdf','ContentType','vector')
exportgraphics(gcf, 'relaxationrates_fL.png', 'Resolution', 300);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Plot the relaxation rate maps (Fig. 4(d-f))
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
N=100;
tt = linspace(0,pi,N);
pp = linspace(0,2*pi,2*N);
Gammas = zeros(N,2*N);

fL = 0.1;
tic
f = plot_Gamma_map_f(dispersion, fL, ld, rho, A, gtensor, hbar);
exportgraphics(f, 'Gamma_map_0.1GHz.png', 'Resolution', 300);
toc
fL = 1;
tic
f = plot_Gamma_map_f(dispersion, fL, ld, rho, A, gtensor, hbar);
exportgraphics(f, 'Gamma_map_1GHz.png', 'Resolution', 300);
toc
fL = 10;
tic
f = plot_Gamma_map_f(dispersion, fL, ld, rho, A, gtensor, hbar);
exportgraphics(f, 'Gamma_map_10GHz.png', 'Resolution', 300);
toc


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Plot the relaxation rate using the analytical formula in Eq. (49) and Eq. (55) for check
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fL = 0.1;
tic
f = plot_Gamma_map_f_analytical(fL, ld, rho, A, E, Iy, C, gtensor, hbar);
saveas(f, 'Gamma_map_1GHz_anal.png');
toc


function f = plot_Gamma_map_f_analytical(fL, ld, rho, A, E, Iy, C, gtensor, hbar)
% Plot the relaxation rates as a function of the magnetic field direction, at a given Larmor frequency using analytical formulas
    N=100;
    tt = linspace(0,pi,N);
    pp = linspace(0,pi,N);
    Gammas = zeros(N,N);
    for i=1:N
        theta = tt(i);
        for j=1:N
            phi = pp(j);
            b=[sin(theta)*cos(phi);sin(theta)*sin(phi);cos(theta)];
            Gammas(i,j) = Gamma_at_f_analytcal(fL*1e9, b, ld, rho, A, E, Iy, C, gtensor, hbar);
        end
    end
    levels = [0.01, 0.05, 0.1, 0.2, 0.5, 1, 2, 4, 8, 14, 20, 30, 50, 70, 100];
    cbLabel = '\Gamma (1/s)';
    plot_title = strcat('Relaxation at f_L = ', string(fL), ' GHz');
    xlabel = '\phi';
    ylabel = '\theta';
    f = plot_logsurface(pp, tt, Gammas, levels, plot_title, xlabel, ylabel, cbLabel);
end


function f = plot_Gamma_map_f(dispersion, fL, ld, rho, A, gtensor, hbar)
% Plot the relaxation rates as a function of the magnetic field direction, at a given Larmor frequency using numerical data
    N=100;
    tt = linspace(0,pi,N);
    pp = linspace(0,pi,N);
    Gammas = zeros(N,N);
    for i=1:N
        theta = tt(i);
        for j=1:N
            phi = pp(j);
            b=[sin(theta)*cos(phi);sin(theta)*sin(phi);cos(theta)];
            Gammas(i,j) = relax_at_f(dispersion, fL, b, ld, rho, A, gtensor, hbar);
        end
    end
    levels = [0.005, 0.01, 0.05, 0.1, 0.2, 0.5, 1, 2, 4, 8, 14, 20, 30, 50, 70, 100];
    cbLabel = 'Relaxation rate, $\Gamma$ (1/s)';
    plot_title = strcat('$f_\mathrm{L} =\,$', string(fL), ' GHz');
    xlabel = '$\phi$';
    ylabel = '$\theta$';
    f = plot_logsurface(pp, tt, Gammas, levels, plot_title, xlabel, ylabel, cbLabel); 
end

function plot_with_inf(xdata, ydata, options)
% Plot functions with infinities
    y_max = max(ydata(~isinf(ydata)));
    y_inf_val = y_max*1e5;
    x_max = max(xdata(~isinf(xdata)));
    x_inf_val = x_max*1e5;
    loglog(min(xdata, x_inf_val),min(ydata, y_inf_val), options);
    xlim([0,x_max]);
    ylim([0,y_max]);
end

function dispersion = read_comsol_file(filename)
% Read the comsol file
    rawdata = readcell(filename);
    data = cell2mat(rawdata(6:end,1:7));
    dispersion = data(data(:,2) > 0,:);
    dispersion = sortrows(dispersion, 2);
end

function plot_dispersions(dispersion, Nmodes)
% Plot the dispersion relations
    for i=1:Nmodes
        ff_mode = dispersion(dispersion(:,7)==i, 1);
        q_mode = real(dispersion(dispersion(:,7)==i, 2))*1e-9;
        scatter(q_mode, ff_mode, 50, "filled", "o");
        hold on;
    end
    hold off;
    % title('Dispersion relation');
    xlabel('wavenumber, $q$ (1/nm)','interpreter','latex');
    ylabel('freqency, $f$ (GHz)','interpreter','latex');
    fontsize(14, "points");
    fontname('Times');
end

function f_der = central_diff(f, fp, fm, hp, hm)
% Central finite difference
    if hp && hm
        f_der = (hm/hp*fp - hp/hm*fm + (hp/hm - hm/hp)*f)/(hp + hm);
    else
        f_der = Inf;
    end
end

function f_der = forward_diff(f, fp, fp2, hp, hp2)
% Forward finite difference
    f_der = ((hp+hp2)^2*fp-(hp2^2+2*hp*hp2)*f - hp^2*fp2)/(hp^2*hp2 + hp2^2*hp);
end

function f_der = backward_diff(f, fm, fm2, hm, hm2)
% Backward finite difference
    f_der = ((hm2^2+2*hm*hm2)*f - (hm+hm2)^2*fm + hm^2*fm2)/(hm^2*hm2 + hm2^2*hm);
end

function DoS = DensiytofStates(ee, qq)
% Calculate the fonon "density of states"
    nf = length(ee);
    DoS = zeros(nf,1);
    DoS(1) = abs(forward_diff(qq(1), qq(2), qq(3), ee(2)-ee(1), ee(3)-ee(2)));
    for i=2:(nf-1)
        hp = ee(i+1) - ee(i);
        hm = ee(i) - ee(i-1);
        DoS(i) = abs(central_diff(qq(i), qq(i+1), qq(i-1), hp, hm));
    end
    DoS(nf) = abs(backward_diff(qq(nf), qq(nf-1), qq(nf-2), ee(nf)-ee(nf-1), ee(nf-1)-ee(nf-2)));
end

function Gamma = relaxation_rate_per_mode(b, fL, q, DoS, omega_array, ld, rho, A, gtensor, hbar)
% Calculate the relaxation rate induced by a given phonon mode
    gfactor = sqrt((gtensor*b)'*(gtensor*b));
    prefactor = hbar^2*2*pi*fL/4/A/rho/gfactor^4.*DoS.*exp(-q.^2.*ld.^2/2);
    nf = length(fL);
    cross_square = zeros(nf, 1);
    for i=1:nf
        omegaq = omega_array(i, :);
        omega_tensor = [
        0, omegaq(1), omegaq(2);
        -omegaq(1), 0, omegaq(3);
        -omegaq(2), -omegaq(3), 0];
        cross_square(i) = subfunction_Gamma(b, omega_tensor, gtensor);
    end
    Gamma = prefactor.*cross_square;
end

function av = subfunction_Gamma(b, omega_tensor, gtensor)
    commutator = omega_tensor*gtensor - gtensor*omega_tensor;
    vect = cross(gtensor*b, commutator*b);
    av = vect'*vect;
end

function [Gamma, ff] = relaxation_from_dispersion_table(dispersion, modes, b, ld, rho, A, gtensor, hbar)
% Calculate the relaxation rate as a function of frequency from numerical data
    ff = unique(dispersion(:,1));
    nf = length(ff);
    Gamma = zeros(nf,1);
    Nrmodes = length(modes);
    for j=1:Nrmodes
        mode=modes(j);
        ff_mode = dispersion(dispersion(:,7)==mode,1); % in GHz !!
        qq_mode = real(dispersion(dispersion(:,7)==mode,2));
        DoS = DensiytofStates(hbar*2*pi*ff_mode*1e9, qq_mode);
        norm = sqrt(dispersion(dispersion(:,7)==mode,3));
        omega_arr = dispersion(dispersion(:,7)==mode,4:6)./norm;
        Gamma_mode = relaxation_rate_per_mode(b, ff_mode*1e9, qq_mode, DoS, omega_arr, ld, rho, A, gtensor, hbar);
        idx = arrayfun(@(x)find(ff==x,1),ff_mode);
        Gamma = Gamma + accumarray(idx, Gamma_mode, [nf,1]);
    end
end

function Gamma = Gamma_at_f_analytcal(f, b, ld, rho, A, E, Iy, C, gtensor, hbar)
% Calculate the relaxation rate analytically for the torsional and flexural modes
    I = 2*Iy;
    GammaT = GammaT_at_f_analytcal(f, b, ld, rho, I, C, gtensor, hbar);
    GammaF = GammaF_at_f_analytcal(f, b, ld, rho, A, E, Iy, gtensor, hbar);
    Gamma = GammaT + GammaF;
end

function Gamma = GammaT_at_f_analytcal(f, b, ld, rho, I, C, gtensor, hbar)
% Calculate the relaxation rate analytically for the torsional mode
    g_perp = gtensor(1,1);
    g_par = gtensor(2,2);
    gamma = g_par/g_perp;
    dgamma = g_perp - g_par;
    A = A_function(b, gamma);
    Gamma = hbar*2*pi*f/4/sqrt(rho*I*C)*dgamma^2/g_perp^2*A*exp(-rho*I*4*pi^2*f^2*ld^2/2/C);
end

function Gamma = GammaF_at_f_analytcal(f, b, ld, rho, A, E, Iy, gtensor, hbar)
% Calculate the relaxation rate analytically for the x directional flexural mode
    g_perp = gtensor(1,1);
    g_par = gtensor(2,2);
    gamma = g_par/g_perp;
    dgamma = g_perp - g_par;
    B = B_function(b, gamma);
    Gamma = (hbar^4*(2*pi*f)^6/rho/A/E^3/Iy^3)^(1/4)/8*dgamma^2/g_perp^2*B*exp(-sqrt(rho*A/E/Iy)*2*pi*f*ld^2/2);
end

function a = A_function(b, gamma)
% The auxiliary function defined in Eq. (50)
    bx = b(1);
    by = b(2);
    bz = b(3);
    a = (bz^2*(bx^2+by^2) + (bx^2-gamma*by^2)^2)/(bx^2 + bz^2 + gamma^2*by^2)^2;
end

function a = B_function(b, gamma)
% The auxiliary function defined in Eq. (56)
    bx = b(1);
    by = b(2);
    bz = b(3);
    a = (bx^2*(bz^2+by^2) + (bz^2-gamma*by^2)^2)/(bx^2 + bz^2 + gamma^2*by^2)^2;
end

function Gamma = relax_at_f(dispersion, fL, b, ld, rho, A, gtensor, hbar)
% Calculate the relaxation rate for a given qubit frequency from the numerical data
    idx = logical((dispersion(:, 1) > fL - 1).*(dispersion(:, 1) < fL + 1));
    reduced_disp = dispersion(idx,:);
    modes = unique(reduced_disp(:,7));
    [Gammas, ff] = relaxation_from_dispersion_table(reduced_disp, modes, b, ld, rho, A, gtensor, hbar);
    [~,idx] = min(abs(ff-fL));
    Gamma = Gammas(idx);
end
